learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views

#Template tagging
app_name = "basicapp"

urlpatterns = [
	path("relative/", views.relative, name="relative"),
	path("other/", views.other, name="other"),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.conf.urls import include

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('basicapp/', include("basicapp.urls")),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context_dict = {"text": "hello world", "number": 100}
	return render(request, "basicapp/index.html", context=context_dict)


def other(request):
	return render(request, "basicapp/other.html")


def relative(request):
	return render(request, "basicapp/relative_url_templates.html")

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <ul class="nav navbar-nav">
            <li class="nav-item"><a class="navbar-brand" href="#">BRAND</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Other</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}

    {% endblock %}
</div>


</body>
</html>

learning_templates/templates/basicapp/index.html
{% extends "basicapp/base.html" %}

{% block body_block %}

<h1>Welcome to index page</h1>
<h2>This is index.html page showing!</h2>
<h3>{{ text|cut:"world" }}</h3>
<h3>{{ number|add:"99" }}</h3>

{% endblock %}

learning_templates/templates/basicapp/other.html
{% extends "basicapp/base.html" %}

{% block body_block %}

<h1>Welcome to other page</h1>
<h2>This is an example of template inheritance</h2>

{% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome to relative url templates page</h1>
<!--<a href="basicapp/other.html">The other page</a>-->
<a href="{% url 'basicapp:other' %}">The other page</a><br>
<a href="{% url 'admin:index' %}">The admin page</a><br>
<a href="{% url 'index' %}">The index page</a><br>
</body>
</html>